# coding: utf-8
from pathlib import Path
from bs4 import BeautifulSoup
import json,html
p=Path('ira/procedure');data=json.loads((p/'amendments.json').read_text());people=json.loads((p/'sponsors.json').read_text());soup=BeautifulSoup(Path('ira/index.html').read_text(),'html.parser');method=soup.find(id='proc-method');method.attrs={}
for a in method.find_all('a',href=True):
 if a['href'].startswith('procedure/'):a['href']=a['href'][10:]
e=html.escape
rows=''.join('<tr><td>'+e(a['id'])+'</td><td>'+e(a['sponsor'])+'</td><td>'+e(a['summary_ko'])+'</td><td>'+e(a['latest_action'])+'</td><td>'+e(a['effect'])+'</td><td><a href="'+e(a['url'])+'">이력</a></td></tr>' for a in reversed(data) if a['floor_proposed'])
peopleRows=''.join('<tr><td>'+e(a['sponsor'])+'</td>'+''.join('<td>'+str(a[k])+'</td>' for k in ['submitted','floor_proposed','agreed','rejected','out_of_order','not_proposed'])+'</tr>' for a in sorted(people,key=lambda a:-a['submitted']))
(p/'report.html').write_text('''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>IRA 양원 절차·수정안 조사</title><style>body{font:16px/1.8 system-ui;max-width:1200px;margin:auto;padding:28px;color:#173c34}table{border-collapse:collapse;width:100%;font-size:13px}th,td{border:1px solid #ccd8d1;padding:9px;vertical-align:top}a{color:#126647}.wide{overflow:auto}nav{display:flex;gap:18px;flex-wrap:wrap}h1{font-size:30px}@media print{body{font-size:10pt}nav{display:none}}</style></head><body><a href="../index.html#proc-route">← 대화형 흐름·검색으로 돌아가기</a><h1>IRA 양원 절차·수정안 조사</h1><p>2026.10.01 · 2021–2022년 입법사 · 주 제출자와 처리 경로 구분</p><nav><a href="#findings">핵심 결과</a><a href="#method">범위·방법</a><a href="#floor">본회의 처리</a><a href="#people">제출자 집계</a></nav><h2 id="findings">핵심 결과</h2><p>H.R.5376 등록 수정안은 295건(상원 293·하원 2)이다. 상원의 27건이 본회의에서 제안됐고 3건 채택, 18건 부결, 6건 절차상 배제로 종료됐다. 266건은 제출 후 본회의 제안·채택 이력이 없다. <a href="BILLSTATUS-117hr5376.xml">공식 BILLSTATUS 원자료</a></p><p>하원은 2021.11.19 BBB를 220–213으로 통과시켰다. 상원은 2022.8.7 IRA로 대체한 법안을 51–50으로 통과시켰고, 하원은 8.12 상원 수정에 220–207로 동의했다. 8.16 서명으로 제정됐다. 슈머의 SA5194 자체는 구두표결로 채택됐으며, 51–50(roll 325)은 법안 전체의 최종 통과다. <a href="../viewer.html?source=R&amp;page=151&amp;evidence=E26">Record S4201</a></p><p>튠 SA5472는 57–43으로 채택됐지만 SALT 공제 한도 연장 부분은 워너 SA5488이 되돌렸다. 최저한세 소득 합산 기준은 §13904에 남았다. §13903은 SALT 관련 조문을 다시 수정하고 비법인 초과사업손실 제한을 연장한다. <a href="../viewer.html?source=P&amp;page=198&amp;evidence=E25">제정법 §13903</a> · <a href="../viewer.html?source=P&amp;page=199&amp;evidence=E24">§13904</a></p><p>민간보험 인슐린 상한 관련 예산규율 면제 동의는 57–43이었으나 60표 미달로 실패했고, 대체안에서 해당 문구가 삭제됐다. 이 절차를 SA5194 전체의 부결이나 별도 등록 수정안으로 세지 않는다. <a href="../viewer.html?source=R&amp;page=144&amp;evidence=E27">Record S4194</a></p><h2 id="method">범위·방법</h2>'''+str(method)+'''<h2 id="floor">본회의 처리 · 상원 27건과 하원 2건</h2><div class="wide"><table><thead><tr><th>번호</th><th>제출자</th><th>목적</th><th>최종 처리 이력</th><th>반영 해석</th><th>출처</th></tr></thead><tbody>'''+rows+'''</tbody></table></div><h2 id="people">주 제출자별 집계</h2><p>Rules Committee의 2건은 하원 특별규칙에 따른 기관 수정안이다. 공동제출자와 대리 제안자는 제출 건수에 더하지 않는다.</p><div class="wide"><table><thead><tr><th>제출자</th><th>제출</th><th>본회의 제안*</th><th>채택</th><th>부결</th><th>절차 배제</th><th>미제안</th></tr></thead><tbody>'''+peopleRows+'</tbody></table></div></body></html>')
