const flowStages=[
 {id:'proposal',date:'2021.05.25–26',title:'미국 조립 조건의 선행 제안',short:'스테이브나우 수정안',region:'미국',start:'제정 5년 뒤',trigger:'상대적 기간으로 제안',role:'스테이브나우: 수정안 명의와 작성자 자기진술',status:'수정안 · 미제정',change:'미국 조립에 대한 추가 공제를 장래의 필수 자격요건으로 전환하도록 제안했습니다.',limit:'2021년 설계의 작성자 진술입니다. 최종 IRA 문구의 작성자 진술로 확대할 수 없습니다.',refs:[['E01','수정안 #1'],['E02','작성자 발언'],['E03','5년 뒤 의무화']],pdf:['T',111,'E02'],compare:['M','J']},
 {id:'bill',date:'2021.06.17 / 06.21 등재',title:'법률 문구에 날짜를 명시',short:'S.2118',region:'미국',start:'2026년부터',trigger:'판매 기준',role:'와이든: 법안 공식 발의',status:'발의안 · 미제정',change:'“2025년 12월 31일 이후 판매”로 날짜를 특정했습니다. 같은 날짜는 5월 26일 JCT 설명서에도 이미 등장합니다.',limit:'6월에 처음 날짜를 정했다는 뜻은 아닙니다. 상대적 기간의 수정안 설명과 고정 날짜의 법률 문구를 구분합니다.',refs:[['E05','5월 JCT 설명'],['E06','S.2118 조문']],pdf:['S',143,'E06'],compare:['S','H']},
 {id:'bbb',date:'2021.11.19 → 12.11',title:'BBB: 2027년 사용 개시 기준',short:'하원 BBB → 상원 초안',region:'미국',start:'2027년부터',trigger:'사용 개시 기준',role:'하원 통과안 → 상원 재무위원회 초안',status:'BBB 법안 단계 · 미제정',change:'지역은 미국으로 유지됩니다. 비교한 S.2118과 달리 날짜는 2027년으로, 적용 사건은 판매에서 사용 개시로 바뀝니다.',limit:'이 날짜를 선택한 개인과 실제 변경 시점은 미확정입니다. 9월 하원 심사자료의 추가 추적이 필요합니다.',refs:[['E09','하원 BBB'],['E11','12월 상원 초안']],pdf:['B',514,'E11'],compare:['B','I']},
 {id:'ira',date:'2022.07.27',title:'두 축이 함께 바뀐 IRA 초안',short:'맨친–슈머 합의 초안',region:'북미',start:'제정일 이후',trigger:'판매 기준',role:'맨친–슈머 합의 초안에 변경된 문구가 등장',status:'공개 합의 초안',change:'① 미국 → 북미로 지역 확대. ② 2027년 사용 개시 → 제정일 이후 판매로 장기 유예 삭제. 두 변경은 늦어도 이 공개 초안에서 확인됩니다.',limit:'북미 확대와 시행일 변경을 각각 누가 요구·작성했는지는 아직 특정되지 않았습니다. 캐나다의 요구는 확인되지만 인과관계는 별도 검증 대상입니다.',refs:[['E13','북미 확대'],['E14','적용 시점 변경'],['E12','캐나다의 사전 요구']],pdf:['I',366,'E13'],compare:['B','I']},
 {id:'law',date:'2022.08.16',title:'북미·제정일 이후 조건으로 제정',short:'IRA 제정법',region:'북미',start:'제정일 이후',trigger:'판매 기준 · 경과조치 존재',role:'슈머: 최종 대체수정안 공식 제출자',status:'제정법',change:'7월 초안의 핵심 지역·시행일 문구가 최종 법률에 유지됩니다. 제정 전 구매·구속력 있는 계약에는 제한적인 경과조치가 있습니다.',limit:'공식 제출자는 개별 문구의 고안자와 동일하지 않을 수 있습니다. “제정일 이후”는 최종 조립 요건의 별도 적용 규정입니다.',refs:[['E16','제출·처리 기록'],['E18','최종 제정 조문'],['E19','경과조치']],pdf:['P',138,'E18'],compare:['I','P']}
];
const flowRoot=document.getElementById('legislative-flow');
if(flowRoot){
 const escapeFlow=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const stageList=flowRoot.querySelector('.flow-stages');
 stageList.innerHTML=flowStages.map((s,i)=>`<li class="flow-step ${i>=3?'north-america':''}"><button type="button" class="stage-button" data-stage="${s.id}" aria-pressed="false" aria-controls="flow-detail"><span class="stage-date">${s.date}</span><span class="stage-node"><span>${String(i+1).padStart(2,'0')}</span><span class="stage-title">${s.short}</span></span><span class="stage-status">${s.status}</span><span class="flow-cell region"><span class="cell-label">조립 지역</span><strong>${s.region}</strong>${i===3?'<span class="change-tag">지역 확대</span>':''}</span><span class="flow-cell timing"><span class="cell-label">의무 적용 시점</span><strong>${s.start}</strong><span class="trigger">${s.trigger}</span>${i===3?'<span class="change-tag">유예 삭제</span>':''}</span><span class="stage-action">근거와 변경 내용 보기 <span aria-hidden="true">↘</span></span></button></li>`).join('');
 function selectStage(id){
  const s=flowStages.find(x=>x.id===id);if(!s)return;
  flowRoot.querySelectorAll('.stage-button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.stage===id)));
  flowRoot.querySelector('#flow-detail').innerHTML=`<div class="detail-heading"><span class="kicker">선택한 단계 · ${escapeFlow(s.date)}</span><h3>${escapeFlow(s.title)}</h3></div><div class="flow-detail-grid"><div><p class="flow-change">${escapeFlow(s.change)}</p><p><b>기록에 나타난 역할</b><br>${escapeFlow(s.role)} · <a href="#actors">인물 설명 →</a></p><div class="flow-evidence">${s.refs.map(([id,label])=>`<a href="#${id}">${id} ${escapeFlow(label)}</a>`).join('')}<a class="flow-pdf" href="viewer.html?source=${s.pdf[0]}&page=${s.pdf[1]}&evidence=${s.pdf[2]}">PDF 하이라이트 ↗</a></div></div><aside class="flow-caution"><b>어디까지 확인됐나</b><p>${escapeFlow(s.limit)}</p><button type="button" class="flow-compare" data-before="${s.compare[0]}" data-after="${s.compare[1]}">이 변화의 조문 나란히 보기 →</button></aside></div>`;
 }
 stageList.addEventListener('click',e=>{const b=e.target.closest('[data-stage]');if(b)selectStage(b.dataset.stage);});
 flowRoot.addEventListener('click',e=>{const b=e.target.closest('.flow-compare');if(!b)return;const before=document.getElementById('before'),after=document.getElementById('after');before.value=b.dataset.before;after.value=b.dataset.after;after.dispatchEvent(new Event('change',{bubbles:true}));location.hash='comparison';});
 selectStage('ira');
}
