/* Local, immutable data only. Submission counts are distinct from floor votes. */
(async()=>{
 const $=id=>document.getElementById(id);if(!$('procedure'))return;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const status={agreed:'채택',rejected:'부결',out_of_order:'절차상 배제',not_proposed:'본회의 미제안'};
 const table=(heads,rows)=>`<table><thead><tr>${heads.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${heads.length}">검색 결과가 없습니다.</td></tr>`}</tbody></table>`;
 const pdf=(source,page,label,evidence='')=>`<a href="viewer.html?source=${source}&amp;page=${page}${evidence?'&amp;evidence='+evidence:''}">${esc(label)}</a>`;
 const goto=id=>{if(location.hash===`#${id}`)window.dispatchEvent(new Event('hashchange'));else location.hash=id;};
 function pager(node,total,page,set){const pages=Math.max(1,Math.ceil(total/12));node.replaceChildren();for(const [label,p,disabled] of [['← 이전',page-1,page===0],['다음 →',page+1,page>=pages-1]]){const b=document.createElement('button');b.type='button';b.textContent=label;b.disabled=disabled;b.onclick=()=>set(p);node.append(b);if(p===page-1){const t=document.createElement('span');t.textContent=`${page+1} / ${pages} · ${total}건`;node.append(t);}}}
 try{
 const [amendments,people,votes,committee]=await Promise.all(['amendments','sponsors','votes','committee'].map(async n=>{const r=await fetch(`procedure/${n}.json`);if(!r.ok)throw Error(n);return r.json();}));
 const byId=new Map(amendments.map(a=>[a.id,a]));let page=0,vpage=0,cpage=0,ppage=0,selected='';
 const anchors=document.createElement('div');anchors.hidden=true;for(const a of amendments){const span=document.createElement('span');span.id=`proc-${a.id}`;anchors.append(span);}$('proc-amendments').append(anchors);
 function filtered(){const query=$('proc-search').value.trim().toLowerCase(),s=$('proc-status').value;return amendments.filter(a=>(s==='all'||s==='floor'&&a.chamber==='Senate'&&a.floor_proposed||s==='house'&&a.chamber==='House'||s===a.status&&a.chamber==='Senate')&&(!query||(byId.has(query.toUpperCase())?a.id===query.toUpperCase():people.some(p=>p.sponsor.toLowerCase()===query)?a.sponsor.toLowerCase()===query:[a.id,a.sponsor,a.summary_ko,a.purpose,a.record_text].join(' ').toLowerCase().includes(query))));}
 function renderAmend(){const rows=filtered();if(selected&&!rows.some(a=>a.id===selected)){selected='';$('proc-detail').innerHTML='<p>수정안을 선택하면 상세 기록이 표시됩니다.</p>';}page=Math.min(page,Math.max(0,Math.ceil(rows.length/12)-1));$('proc-results').textContent=`${rows.length}건 · 한 페이지에 최대 12건. 번호를 선택하면 아래에 상세 기록이 표시됩니다.`;$('proc-amend-table').innerHTML=table(['수정안','주 제출자 / 제출일','목적','결과'],rows.slice(page*12,page*12+12).map(a=>`<tr aria-selected="${a.id===selected}"><td><button data-amend="${a.id}">${a.id}</button></td><td>${esc(a.sponsor)}<small>${a.submitted}</small></td><td>${esc(a.summary_ko)}${a.purpose?`<small lang="en">${esc(a.purpose)}</small>`:''}</td><td>${status[a.status]||esc(a.status)}</td></tr>`));pager($('proc-pager'),rows.length,page,p=>{page=p;renderAmend();});}
 function detail(id,focus=false){const a=byId.get(id);if(!a)return;selected=id;const av=votes.filter(v=>v.related_amendments.includes(id));const dedup=[...new Map(a.actions.map(x=>[x.date+'|'+x.text,x])).values()].sort((x,y)=>x.date.localeCompare(y.date));const key={SA5472:'E24',SA5488:'E25',SA5194:'E26'}[id];$('proc-detail').innerHTML=`<h3>${a.id} · ${esc(a.summary_ko)}</h3><p><b>${esc(a.sponsor)}</b> · ${a.chamber==='Senate'?'상원':'하원'} · ${status[a.status]}</p><p>제출 ${a.submitted} / 본회의 제안 ${a.proposed|| (a.chamber==='House'?'특별규칙에 따라 채택':'기록 없음')} · 수정 대상 ${a.parent}</p><p lang="en">${esc(a.purpose||'공식 목적란 미기재 — 아래 원문 참조')}</p><p><b>반영 여부</b> ${esc(a.effect)}</p>${av.map(v=>`<p><b>${v.date} · roll ${v.number} · ${esc(v.kind)}</b> : ${v.yes}–${v.no} · ${esc(v.result)} <a href="${esc(v.url)}">표결 원기록 ↗</a></p>`).join('')}${id==='SA5194'?'<p>위 roll 314는 일부 문구에 대한 예산규율 면제 동의입니다. 대체안 전체 채택은 구두표결, 법안 전체 통과는 roll 325입니다.</p>':''}<p><a href="${esc(a.url)}">Congress.gov 수정안 이력 ↗</a>${a.record_page?' · '+pdf('R',a.record_page,`제출 원문 PDF ${a.record_page}쪽`):''}${key?' · '+pdf('R',id==='SA5472'?150:151,'핵심 처리 원문 강조',key):''}</p><details open><summary>공식 처리 이력 · 날짜순</summary><ol class="proc-history">${dedup.map(x=>`<li><b>${x.date}</b> <span lang="en">${esc(x.text)}</span></li>`).join('')}</ol></details>${a.record_text?`<details><summary>검색용 제출 원문 텍스트</summary><p class="proc-caption">PDF 기계 추출입니다. 다단 편집 때문에 문장 순서·줄바꿈이 달라질 수 있으므로 인용은 PDF에서 확인하세요.</p><pre lang="en">${esc(a.record_text)}</pre></details>`:''}`;renderAmend();if(focus)$('proc-detail').focus({preventScroll:true});}
 function renderPeople(){const q=$('proc-person-search').value.toLowerCase();const rows=people.filter(p=>p.sponsor.toLowerCase().includes(q)).sort((a,b)=>b.submitted-a.submitted||a.sponsor.localeCompare(b.sponsor));$('proc-person-table').innerHTML=table(['주 제출자','제출','본회의 제안¹','채택','부결','절차 배제','미제안'],rows.slice(ppage*12,ppage*12+12).map(p=>`<tr><td><button data-person="${esc(p.sponsor)}">${esc(p.sponsor)}</button></td>${['submitted','floor_proposed','agreed','rejected','out_of_order','not_proposed'].map(k=>`<td>${p[k]}</td>`).join('')}</tr>`))+'<p class="proc-caption">¹ 하원 Rules Committee의 2건은 특별규칙에 따라 채택된 항목입니다. 상원식 개별 floor 제안 27건과 구분됩니다.</p>';pager($('proc-person-pager'),rows.length,ppage,p=>{ppage=p;renderPeople();});}
 const kinds=[...new Set(votes.map(v=>v.kind))];for(const kind of kinds){const o=document.createElement('option');o.value=kind;o.textContent=kind;$('proc-vote-kind').append(o);}
 function renderVotes(){const rows=votes.filter(v=>$('proc-vote-kind').value==='all'||v.kind===$('proc-vote-kind').value);$('proc-vote-table').innerHTML=table(['날짜 / 의회','표결 질문','찬성–반대','결과·수정안','근거'],rows.slice(vpage*12,vpage*12+12).map(v=>`<tr><td>${v.date}<small>${v.chamber==='Senate'?'상원':'하원'} · roll ${v.number}</small></td><td>${esc(v.kind)}<details><summary>원문 질문</summary>${esc(v.description)}</details></td><td><b>${v.yes}–${v.no}</b>${v.yes===51&&v.no===50?'<small>부통령 찬성 포함</small>':''}</td><td>${v.result}${v.related_amendments.map(id=>` <button data-amend="${id}">${id}</button>`).join('')}</td><td><a href="${esc(v.url)}">표결 출처 ↗</a>${v.record_pages?.length?'<br>'+pdf('R',v.record_pages[0],`PDF ${v.record_pages[0]}쪽`):''}</td></tr>`));pager($('proc-vote-pager'),rows.length,vpage,p=>{vpage=p;renderVotes();});}
 const committeeCounts=new Map();committee.forEach(a=>committeeCounts.set(a.sponsor,(committeeCounts.get(a.sponsor)||0)+1));$('proc-committee-counts').innerHTML=table(['주 제출자','목록 건수'],[...committeeCounts].sort((a,b)=>b[1]-a[1]).map(([n,c])=>`<tr><td>${esc(n)}</td><td>${c}</td></tr>`));
 function renderCommittee(){const q=$('proc-committee-search').value.toLowerCase(),rows=committee.filter(a=>[a.sponsor,a.number,a.title,a.summary,a.status].join(' ').toLowerCase().includes(q));$('proc-committee-table').innerHTML=table(['제출자 / 원문 번호','목적','처리·발언 대조','근거'],rows.slice(cpage*12,cpage*12+12).map(a=>`<tr><td>${esc(a.sponsor)} #${a.number}</td><td>${esc(a.title)}${a.summary?`<small>${esc(a.summary)}</small>`:''}</td><td>${esc(a.status)}</td><td>${pdf('M',a.page,`제출목록 ${a.page}쪽`)}${a.transcript_page?'<br>'+pdf('T',a.transcript_page,`속기록 ${a.transcript_page}쪽`):''}</td></tr>`));pager($('proc-committee-pager'),rows.length,cpage,p=>{cpage=p;renderCommittee();});}
 $('proc-search').oninput=()=>{page=0;renderAmend();};$('proc-status').onchange=()=>{page=0;renderAmend();};$('proc-clear').onclick=()=>{$('proc-search').value='';$('proc-status').value='floor';page=0;renderAmend();};$('proc-person-search').oninput=()=>{ppage=0;renderPeople();};$('proc-vote-kind').onchange=()=>{vpage=0;renderVotes();};$('proc-committee-search').oninput=()=>{cpage=0;renderCommittee();};
 $('procedure').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.amend){goto(`proc-${b.dataset.amend}`);}if(b.dataset.status){$('proc-status').value=b.dataset.status;$('proc-search').value='';page=0;renderAmend();goto('proc-amendments');}if(b.dataset.person){$('proc-search').value=b.dataset.person;$('proc-status').value='all';page=0;renderAmend();goto('proc-amendments');}});
 function route(){const id=location.hash.replace('#proc-','');if(byId.has(id)){const a=byId.get(id);$('proc-search').value=id;$('proc-status').value='all';page=0;detail(a.id);}}
 window.addEventListener('hashchange',route);window.addEventListener('popstate',route);renderPeople();renderAmend();renderVotes();renderCommittee();route();if(location.hash.startsWith('#proc-SA')||location.hash.startsWith('#proc-HA'))window.dispatchEvent(new Event('hashchange'));
 }catch(error){$('proc-results').textContent='자료를 불러오지 못했습니다. 새로고침하거나 범위·자료 받기 탭에서 CSV를 열어 주세요.';console.error(error);}
})();
